/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package didactic.fiesta

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
